name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build \
           --build-arg REACT_APP_API_BASE_URL= \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-frontend:latest \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-frontend:${{ github.sha }} \
            -f neu-chatbot/Dockerfile \
            neu-chatbot
      
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-frontend:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-frontend:${{ github.sha }}
      
      - name: Build and Push neu-chatbot-backend Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/neu-chatbot-backend:latest \
                  -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/neu-chatbot-backend:${{ github.sha }} \
                  ./neu-chatbot-backend
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/neu-chatbot-backend:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/neu-chatbot-backend:${{ github.sha }}       
     
      - name: Build and Push Python Service Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/python-service:latest \
                  -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/python-service:${{ github.sha }} \
                  ./python-service
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/python-service:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/python-service:${{ github.sha }}
      
      - name: Deploy to Vertex AI
        run: |
          gcloud run deploy python-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/python-service:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
           

